/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;

/**
 *
 * @author jerem
 */
public class Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroClientes
     */
    public Clientes() {
        initComponents();
    }
    
    public void validarNombre(){
        if(txtnombrecli.getText().isEmpty()){
            lblobligatorio.setText("(*) Este es un campo obligatorio");
        }else{
            lblobligatorio.setText("");
        }
        if(txtnombrecli.getText().isEmpty()){
            btnguardar.setEnabled(false);
        }else{
            btnguardar.setEnabled(true);
        }
    }
    
    public void validarDNI(){
        if(txtdnicli.getText().isEmpty()){
            lblobligatorio1.setText("(*) Este es un campo obligatorio");
        }else{
            lblobligatorio1.setText("");
        }
        if(txtdnicli.getText().isEmpty()){
            btnguardar.setEnabled(false);
        }else{
            btnguardar.setEnabled(true);
        }
    }
    
    public void validarTelefono(){
        if(txttelefonocli.getText().isEmpty()){
            lblobligatorio2.setText("(*) Este es un campo obligatorio");
        }else{
            lblobligatorio2.setText("");
        }
        if(txttelefonocli.getText().isEmpty()){
            btnguardar.setEnabled(false);
        }else{
            btnguardar.setEnabled(true);
        }
    }
    public void validarDireccion(){
        if(txtdireccioncli.getText().isEmpty()){
            lblobligatorio3.setText("(*) Este es un campo obligatorio");
        }else{
            lblobligatorio3.setText("");
        }
        if(txtdireccioncli.getText().isEmpty()){
            btnguardar.setEnabled(false);
        }else{
            btnguardar.setEnabled(true);
        }
    }
    
    public void validarBusqueda(){
        if(txtbuscarcli.getText().isEmpty()){
            lblobligatorio4.setText("(*) Este es un campo obligatorio");
        }else{
            lblobligatorio4.setText("");
        }
        if(txtbuscarcli.getText().isEmpty()){
            btnbuscarcli.setEnabled(false);
            btnregistrarcli.setEnabled(false);
            btneditarcli.setEnabled(false);
            btnactivarcli.setEnabled(false);
            btndesactivarcli.setEnabled(false);
        }else{
            btnbuscarcli.setEnabled(true);
            btnregistrarcli.setEnabled(true);
            btneditarcli.setEnabled(true);
            btnactivarcli.setEnabled(true);
            btndesactivarcli.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbuscarcli = new javax.swing.JTextField();
        btnbuscarcli = new javax.swing.JButton();
        btnregistrarcli = new javax.swing.JButton();
        btneditarcli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnactivarcli = new javax.swing.JButton();
        btndesactivarcli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblobligatorio4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombrecli = new javax.swing.JTextField();
        txtdnicli = new javax.swing.JTextField();
        txttelefonocli = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdireccioncli = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblobligatorio = new javax.swing.JLabel();
        lblobligatorio1 = new javax.swing.JLabel();
        lblobligatorio2 = new javax.swing.JLabel();
        lblobligatorio3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/clientes.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/nombrecliente.png"))); // NOI18N
        jLabel1.setText("Nombre del Clientes");

        txtbuscarcli.setForeground(new java.awt.Color(153, 153, 153));
        txtbuscarcli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbuscarcli.setText("Buscar...");
        txtbuscarcli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbuscarcliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbuscarcliFocusLost(evt);
            }
        });
        txtbuscarcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarcliKeyReleased(evt);
            }
        });

        btnbuscarcli.setBackground(new java.awt.Color(255, 255, 204));
        btnbuscarcli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbuscarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/lupa.png"))); // NOI18N
        btnbuscarcli.setText("Buscar Cliente");

        btnregistrarcli.setBackground(new java.awt.Color(255, 255, 204));
        btnregistrarcli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnregistrarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/registrarpersona.png"))); // NOI18N
        btnregistrarcli.setText("Registrar Cliente");

        btneditarcli.setBackground(new java.awt.Color(255, 255, 204));
        btneditarcli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btneditarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/editar.png"))); // NOI18N
        btneditarcli.setText("Editar Cliente");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnactivarcli.setBackground(new java.awt.Color(102, 255, 102));
        btnactivarcli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnactivarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/check.png"))); // NOI18N
        btnactivarcli.setText("Activar Cliente");

        btndesactivarcli.setBackground(new java.awt.Color(255, 102, 102));
        btndesactivarcli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndesactivarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/x.png"))); // NOI18N
        btndesactivarcli.setText("Desactivar Cliente");

        jLabel2.setText("TOTAL DE REGISTROS");

        lblobligatorio4.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio4.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnactivarcli)
                        .addGap(18, 18, 18)
                        .addComponent(btndesactivarcli)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblobligatorio4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtbuscarcli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnbuscarcli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnregistrarcli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneditarcli)))))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbuscarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarcli)
                    .addComponent(btnregistrarcli)
                    .addComponent(btneditarcli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblobligatorio4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnactivarcli)
                            .addComponent(btndesactivarcli)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado de Clientes", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/registrarpersona.png"))); // NOI18N
        jLabel3.setText("Nombre del Cliente *");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/tipodocumento.png"))); // NOI18N
        jLabel4.setText(" DNI *");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/telefono.png"))); // NOI18N
        jLabel5.setText(" Telefono *");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/direccion.png"))); // NOI18N
        jLabel6.setText(" Dirección *");

        txtnombrecli.setForeground(new java.awt.Color(153, 153, 153));
        txtnombrecli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombrecli.setText("Ingresar nombre");
        txtnombrecli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnombrecliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombrecliFocusLost(evt);
            }
        });
        txtnombrecli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombrecliKeyReleased(evt);
            }
        });

        txtdnicli.setForeground(new java.awt.Color(153, 153, 153));
        txtdnicli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdnicli.setText("Ingresar número de documento");
        txtdnicli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdnicliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdnicliFocusLost(evt);
            }
        });
        txtdnicli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdnicliKeyReleased(evt);
            }
        });

        txttelefonocli.setForeground(new java.awt.Color(153, 153, 153));
        txttelefonocli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttelefonocli.setText("N° de telefono");
        txttelefonocli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelefonocliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelefonocliFocusLost(evt);
            }
        });
        txttelefonocli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonocliActionPerformed(evt);
            }
        });
        txttelefonocli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelefonocliKeyReleased(evt);
            }
        });

        txtdireccioncli.setColumns(20);
        txtdireccioncli.setForeground(new java.awt.Color(153, 153, 153));
        txtdireccioncli.setRows(5);
        txtdireccioncli.setText("Añade una dirección");
        txtdireccioncli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdireccioncliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdireccioncliFocusLost(evt);
            }
        });
        txtdireccioncli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccioncliKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtdireccioncli);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Los campos obligatorios están marcados con un asterisco (*).");

        jButton6.setBackground(new java.awt.Color(0, 204, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/cancel_1.png"))); // NOI18N
        jButton6.setText(" Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(102, 255, 204));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/guardar.png"))); // NOI18N
        btnguardar.setText(" Guardar");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("(*) Este es un campo obligatorio");

        lblobligatorio.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio.setForeground(new java.awt.Color(255, 51, 51));

        lblobligatorio1.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio1.setForeground(new java.awt.Color(255, 51, 51));

        lblobligatorio2.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio2.setForeground(new java.awt.Color(255, 51, 51));

        lblobligatorio3.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio3.setForeground(new java.awt.Color(255, 51, 51));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/clientesperro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(lblobligatorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtdnicli, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblobligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtnombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblobligatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txttelefonocli, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblobligatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel7)))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(32, 32, 32)
                                .addComponent(btnguardar))
                            .addComponent(jLabel8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(513, 513, 513)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lblobligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdnicli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblobligatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttelefonocli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblobligatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblobligatorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Formulario de Clientes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefonocliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonocliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonocliActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtnombrecliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrecliKeyReleased
        validarNombre();
    }//GEN-LAST:event_txtnombrecliKeyReleased

    private void txtdnicliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdnicliKeyReleased
        validarDNI();
    }//GEN-LAST:event_txtdnicliKeyReleased

    private void txttelefonocliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonocliKeyReleased
        validarTelefono();
    }//GEN-LAST:event_txttelefonocliKeyReleased

    private void txtdireccioncliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccioncliKeyReleased
        validarDireccion();
    }//GEN-LAST:event_txtdireccioncliKeyReleased

    private void txtbuscarcliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarcliKeyReleased
        validarBusqueda();
    }//GEN-LAST:event_txtbuscarcliKeyReleased

    private void txtbuscarcliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarcliFocusGained
        if(txtbuscarcli.getText().equals("Buscar...")){
            txtbuscarcli.setText("");
            txtbuscarcli.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtbuscarcliFocusGained

    private void txtbuscarcliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarcliFocusLost
        if(txtbuscarcli.getText().equals("")){
            txtbuscarcli.setText("Buscar...");
            txtbuscarcli.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtbuscarcliFocusLost

    private void txtnombrecliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombrecliFocusGained
        if(txtnombrecli.getText().equals("Ingresar nombre")){
            txtnombrecli.setText("");
            txtnombrecli.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtnombrecliFocusGained

    private void txtnombrecliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombrecliFocusLost
        if(txtnombrecli.getText().equals("")){
            txtnombrecli.setText("Ingresar nombre");
            txtnombrecli.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtnombrecliFocusLost

    private void txtdnicliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdnicliFocusGained
       if(txtdnicli.getText().equals("Ingresar número de documento")){
           txtdnicli.setText("");
           txtdnicli.setForeground(Color.BLACK);
       }
    }//GEN-LAST:event_txtdnicliFocusGained

    private void txtdnicliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdnicliFocusLost
        if(txtdnicli.getText().equals("")){
           txtdnicli.setText("Ingresar número de documento");
           txtdnicli.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtdnicliFocusLost

    private void txttelefonocliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefonocliFocusGained
        if(txttelefonocli.getText().equals("N° de telefono")){
            txttelefonocli.setText("");
            txttelefonocli.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txttelefonocliFocusGained

    private void txttelefonocliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefonocliFocusLost
        if(txttelefonocli.getText().equals("")){
            txttelefonocli.setText("N° de telefono");
            txttelefonocli.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txttelefonocliFocusLost

    private void txtdireccioncliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdireccioncliFocusGained
        if(txtdireccioncli.getText().equals("Añade una dirección")){
            txtdireccioncli.setText("");
            txtdireccioncli.setForeground(Color.BLACK);           
        }
    }//GEN-LAST:event_txtdireccioncliFocusGained

    private void txtdireccioncliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdireccioncliFocusLost
        if(txtdireccioncli.getText().equals("")){
            txtdireccioncli.setText("Añade una dirección");
            txtdireccioncli.setForeground(Color.GRAY); 
        }
    }//GEN-LAST:event_txtdireccioncliFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactivarcli;
    private javax.swing.JButton btnbuscarcli;
    private javax.swing.JButton btndesactivarcli;
    private javax.swing.JButton btneditarcli;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnregistrarcli;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblobligatorio;
    private javax.swing.JLabel lblobligatorio1;
    private javax.swing.JLabel lblobligatorio2;
    private javax.swing.JLabel lblobligatorio3;
    private javax.swing.JLabel lblobligatorio4;
    private javax.swing.JTextField txtbuscarcli;
    private javax.swing.JTextArea txtdireccioncli;
    private javax.swing.JTextField txtdnicli;
    private javax.swing.JTextField txtnombrecli;
    private javax.swing.JTextField txttelefonocli;
    // End of variables declaration//GEN-END:variables
}
