/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;

/**
 *
 * @author User
 */
public class Pacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pacientes
     */
    public Pacientes() {
        initComponents();
    }
    
    public void validarBusqueda(){
        if(txtbuscarpacientes.getText().isEmpty()){
            lblobligatoriobuscarpa.setText("(*) Campo obligatorio");
        }else{
            lblobligatoriobuscarpa.setText("");
        }
        if(txtbuscarpacientes.getText().isEmpty()){
            btnbuscarpa.setEnabled(false);
            btnregistrarpa.setEnabled(false);
            btneditarpa.setEnabled(false);
            btnactivarpa.setEnabled(false);
            btndesactivarpa.setEnabled(false);
        }else{
            btnbuscarpa.setEnabled(true);
            btnregistrarpa.setEnabled(true);
            btneditarpa.setEnabled(true);
            btnactivarpa.setEnabled(true);
            btndesactivarpa.setEnabled(true);
        }
    }
    
    public void validarDNICli(){
        if(txtdocumentocli1.getText().isEmpty()){
            lblobligatorio6.setText("(*) Campo obligatorio");
        }else{
            lblobligatorio6.setText("");
        }
        if(txtdocumentocli1.getText().isEmpty()){
            btnguardarpaci.setEnabled(false);
        }else{
            btnguardarpaci.setEnabled(true);
        }
    }
    public void validarNombrePa(){
        if(txtnombrepaci.getText().isEmpty()){
            lblobligatorio7.setText("(*) Campo obligatorio");
        }else{
            lblobligatorio7.setText("");
        }
        if(txtnombrepaci.getText().isEmpty()){
            btnguardarpaci.setEnabled(false);
        }else{
            btnguardarpaci.setEnabled(true);
        }
    }
    public void validarEdadPa(){
        if(txtedadpa.getText().isEmpty()){
            lblobligatorio8.setText("(*) Campo obligatorio");
        }else{
            lblobligatorio8.setText("");
        }
        if(txtedadpa.getText().isEmpty()){
            btnguardarpaci.setEnabled(false);
        }else{
            btnguardarpaci.setEnabled(true);
        }
    }
    public void validarColorPa(){
        if(txtcolorpa.getText().isEmpty()){
            lblobligatorio9.setText("(*) Campo obligatorio");
        }else{
            lblobligatorio9.setText("");
        }
        if(txtcolorpa.getText().isEmpty()){
            btnguardarpaci.setEnabled(false);
        }else{
            btnguardarpaci.setEnabled(true);
        }
    }
    public void validarRazaPa(){
        if(txtrazapa.getText().isEmpty()){
            lblobligatorio10.setText("(*) Campo obligatorio");
        }else{
            lblobligatorio10.setText("");
        }
        if(txtrazapa.getText().isEmpty()){
            btnguardarpaci.setEnabled(false);
        }else{
            btnguardarpaci.setEnabled(true);
        }
    }
    public void validarPesoPa(){
        if(txtpesopa.getText().isEmpty()){
            lblobligatorio11.setText("(*) Campo obligatorio");
        }else{
            lblobligatorio11.setText("");
        }
        if(txtpesopa.getText().isEmpty()){
            btnguardarpaci.setEnabled(false);
        }else{
            btnguardarpaci.setEnabled(true);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbuscarpacientes = new javax.swing.JTextField();
        btnbuscarpa = new javax.swing.JButton();
        btnregistrarpa = new javax.swing.JButton();
        btneditarpa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnactivarpa = new javax.swing.JButton();
        btndesactivarpa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblobligatoriobuscarpa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtdocumentocli1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnombrepaci = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtedadpa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcolorpa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtrazapa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpesopa = new javax.swing.JTextField();
        btnguardarpaci = new javax.swing.JButton();
        btncancelarpaci = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblobligatorio6 = new javax.swing.JLabel();
        lblobligatorio10 = new javax.swing.JLabel();
        lblobligatorio7 = new javax.swing.JLabel();
        lblobligatorio11 = new javax.swing.JLabel();
        lblobligatorio8 = new javax.swing.JLabel();
        lblobligatorio9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pacientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/wauwau.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/wauwau.png"))); // NOI18N
        jLabel1.setText("Nombre del Paciente");

        txtbuscarpacientes.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscarpacientes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbuscarpacientes.setText("Buscar...");
        txtbuscarpacientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbuscarpacientesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbuscarpacientesFocusLost(evt);
            }
        });
        txtbuscarpacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarpacientesActionPerformed(evt);
            }
        });
        txtbuscarpacientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarpacientesKeyReleased(evt);
            }
        });

        btnbuscarpa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbuscarpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/lupa.png"))); // NOI18N
        btnbuscarpa.setText("Buscar Paciente");

        btnregistrarpa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnregistrarpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/+.png"))); // NOI18N
        btnregistrarpa.setText(" Registar Paciente");
        btnregistrarpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarpaActionPerformed(evt);
            }
        });

        btneditarpa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btneditarpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/editar.png"))); // NOI18N
        btneditarpa.setText("Editar Paciente");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnactivarpa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnactivarpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/check.png"))); // NOI18N
        btnactivarpa.setText("Activar Cliente");

        btndesactivarpa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndesactivarpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/x.png"))); // NOI18N
        btndesactivarpa.setText("Desactivar Cliente");

        jLabel2.setText("TOTAL DE REGISTROS");

        lblobligatoriobuscarpa.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatoriobuscarpa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatoriobuscarpa.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblobligatoriobuscarpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbuscarpacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscarpa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnregistrarpa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneditarpa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnactivarpa)
                                .addGap(18, 18, 18)
                                .addComponent(btndesactivarpa)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbuscarpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarpa)
                    .addComponent(btnregistrarpa)
                    .addComponent(btneditarpa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblobligatoriobuscarpa, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactivarpa)
                    .addComponent(btndesactivarpa)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado de Pacientes", jPanel1);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/polar.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/perro1.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/tipodocumento.png"))); // NOI18N
        jLabel5.setText(" DNI del Cliente *");

        txtdocumentocli1.setForeground(new java.awt.Color(153, 153, 153));
        txtdocumentocli1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdocumentocli1.setText("N° documento");
        txtdocumentocli1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdocumentocli1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdocumentocli1FocusLost(evt);
            }
        });
        txtdocumentocli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentocli1ActionPerformed(evt);
            }
        });
        txtdocumentocli1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdocumentocli1KeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/wauwau.png"))); // NOI18N
        jLabel6.setText(" Nombre del Paciente *");

        txtnombrepaci.setForeground(new java.awt.Color(153, 153, 153));
        txtnombrepaci.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombrepaci.setText("Nombre Paciente");
        txtnombrepaci.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnombrepaciFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombrepaciFocusLost(evt);
            }
        });
        txtnombrepaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrepaciActionPerformed(evt);
            }
        });
        txtnombrepaci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombrepaciKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/edad.png"))); // NOI18N
        jLabel7.setText(" Edad del Paciente *");

        txtedadpa.setForeground(new java.awt.Color(153, 153, 153));
        txtedadpa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtedadpa.setText("Edad");
        txtedadpa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtedadpaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtedadpaFocusLost(evt);
            }
        });
        txtedadpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtedadpaActionPerformed(evt);
            }
        });
        txtedadpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtedadpaKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/condicion.png"))); // NOI18N
        jLabel8.setText(" Color del Paciente *");

        txtcolorpa.setForeground(new java.awt.Color(153, 153, 153));
        txtcolorpa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcolorpa.setText("Color");
        txtcolorpa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcolorpaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcolorpaFocusLost(evt);
            }
        });
        txtcolorpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcolorpaActionPerformed(evt);
            }
        });
        txtcolorpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcolorpaKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/raza.png"))); // NOI18N
        jLabel9.setText("Raza del Paciente *");

        txtrazapa.setForeground(new java.awt.Color(153, 153, 153));
        txtrazapa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtrazapa.setText("Raza");
        txtrazapa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtrazapaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtrazapaFocusLost(evt);
            }
        });
        txtrazapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrazapaActionPerformed(evt);
            }
        });
        txtrazapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrazapaKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/kg.png"))); // NOI18N
        jLabel10.setText(" Peso del Paciente *");

        txtpesopa.setForeground(new java.awt.Color(153, 153, 153));
        txtpesopa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpesopa.setText("Peso");
        txtpesopa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpesopaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpesopaFocusLost(evt);
            }
        });
        txtpesopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesopaActionPerformed(evt);
            }
        });
        txtpesopa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesopaKeyReleased(evt);
            }
        });

        btnguardarpaci.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnguardarpaci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/guardar.png"))); // NOI18N
        btnguardarpaci.setText(" Guardar");

        btncancelarpaci.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncancelarpaci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/cancel_1.png"))); // NOI18N
        btncancelarpaci.setText(" Cancelar");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setText("Los campos obligatorios están marcados con un asterisco (*).");

        lblobligatorio6.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio6.setForeground(new java.awt.Color(255, 51, 51));

        lblobligatorio10.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio10.setForeground(new java.awt.Color(255, 51, 51));

        lblobligatorio7.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio7.setForeground(new java.awt.Color(255, 51, 51));

        lblobligatorio11.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio11.setForeground(new java.awt.Color(255, 51, 51));

        lblobligatorio8.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio8.setForeground(new java.awt.Color(255, 51, 51));

        lblobligatorio9.setBackground(new java.awt.Color(255, 255, 255));
        lblobligatorio9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblobligatorio9.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5))
                            .addComponent(txtdocumentocli1)
                            .addComponent(txtnombrepaci, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(txtedadpa)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(lblobligatorio6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblobligatorio7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblobligatorio8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(txtpesopa, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(txtcolorpa)
                            .addComponent(txtrazapa)
                            .addComponent(lblobligatorio10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblobligatorio11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblobligatorio9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnguardarpaci)
                                .addGap(27, 27, 27)
                                .addComponent(btncancelarpaci))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdocumentocli1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcolorpa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblobligatorio6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtrazapa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnombrepaci, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblobligatorio10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblobligatorio7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblobligatorio9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(txtedadpa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel3))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnguardarpaci)
                                    .addComponent(btncancelarpaci))))
                        .addGap(4, 4, 4)
                        .addComponent(txtpesopa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblobligatorio11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblobligatorio8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Formulario de Pacientes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistrarpaActionPerformed

    private void txtedadpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtedadpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtedadpaActionPerformed

    private void txtbuscarpacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarpacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarpacientesActionPerformed

    private void txtdocumentocli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentocli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentocli1ActionPerformed

    private void txtnombrepaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrepaciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrepaciActionPerformed

    private void txtcolorpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcolorpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcolorpaActionPerformed

    private void txtrazapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrazapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrazapaActionPerformed

    private void txtpesopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesopaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesopaActionPerformed

    private void txtbuscarpacientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarpacientesKeyReleased
        validarBusqueda();
    }//GEN-LAST:event_txtbuscarpacientesKeyReleased

    private void txtdocumentocli1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentocli1KeyReleased
        validarDNICli();
    }//GEN-LAST:event_txtdocumentocli1KeyReleased

    private void txtnombrepaciKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrepaciKeyReleased
        validarNombrePa();
    }//GEN-LAST:event_txtnombrepaciKeyReleased

    private void txtedadpaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedadpaKeyReleased
        validarEdadPa();
    }//GEN-LAST:event_txtedadpaKeyReleased

    private void txtcolorpaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcolorpaKeyReleased
        validarColorPa();
    }//GEN-LAST:event_txtcolorpaKeyReleased

    private void txtrazapaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrazapaKeyReleased
        validarRazaPa();
    }//GEN-LAST:event_txtrazapaKeyReleased

    private void txtpesopaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesopaKeyReleased
       validarPesoPa();
    }//GEN-LAST:event_txtpesopaKeyReleased

    private void txtbuscarpacientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarpacientesFocusGained
        if(txtbuscarpacientes.getText().equals("Buscar...")){
            txtbuscarpacientes.setText("");
            txtbuscarpacientes.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtbuscarpacientesFocusGained

    private void txtbuscarpacientesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarpacientesFocusLost
        if(txtbuscarpacientes.getText().equals("")){
            txtbuscarpacientes.setText("Buscar...");
            txtbuscarpacientes.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtbuscarpacientesFocusLost

    private void txtdocumentocli1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdocumentocli1FocusGained
        if(txtdocumentocli1.getText().equals("N° documento")){
            txtdocumentocli1.setText("");
            txtdocumentocli1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtdocumentocli1FocusGained

    private void txtdocumentocli1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdocumentocli1FocusLost
        if(txtdocumentocli1.getText().equals("")){
            txtdocumentocli1.setText("N° documento");
            txtdocumentocli1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtdocumentocli1FocusLost

    private void txtnombrepaciFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombrepaciFocusGained
        if(txtnombrepaci.getText().equals("Nombre Paciente")){
            txtnombrepaci.setText("");
            txtnombrepaci.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtnombrepaciFocusGained

    private void txtnombrepaciFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombrepaciFocusLost
        if(txtnombrepaci.getText().equals("")){
            txtnombrepaci.setText("Nombre Paciente");
            txtnombrepaci.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtnombrepaciFocusLost

    private void txtedadpaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtedadpaFocusGained
        if(txtedadpa.getText().equals("Edad")){
            txtedadpa.setText("");
            txtedadpa.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtedadpaFocusGained

    private void txtedadpaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtedadpaFocusLost
        if(txtedadpa.getText().equals("")){
            txtedadpa.setText("Edad");
            txtedadpa.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtedadpaFocusLost

    private void txtcolorpaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcolorpaFocusGained
        if(txtcolorpa.getText().equals("Color")){
            txtcolorpa.setText("");
            txtcolorpa.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtcolorpaFocusGained

    private void txtcolorpaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcolorpaFocusLost
        if(txtcolorpa.getText().equals("")){
            txtcolorpa.setText("Color");
            txtcolorpa.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtcolorpaFocusLost

    private void txtrazapaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrazapaFocusGained
        if(txtrazapa.getText().equals("Raza")){
            txtrazapa.setText("");
            txtrazapa.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtrazapaFocusGained

    private void txtrazapaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrazapaFocusLost
        if(txtrazapa.getText().equals("")){
            txtrazapa.setText("Raza");
            txtrazapa.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtrazapaFocusLost

    private void txtpesopaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpesopaFocusGained
        if(txtpesopa.getText().equals("Peso")){
            txtpesopa.setText("");
            txtpesopa.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtpesopaFocusGained

    private void txtpesopaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpesopaFocusLost
        if(txtpesopa.getText().equals("")){
            txtpesopa.setText("Peso");
            txtpesopa.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtpesopaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactivarpa;
    private javax.swing.JButton btnbuscarpa;
    private javax.swing.JButton btncancelarpaci;
    private javax.swing.JButton btndesactivarpa;
    private javax.swing.JButton btneditarpa;
    private javax.swing.JButton btnguardarpaci;
    private javax.swing.JButton btnregistrarpa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblobligatorio10;
    private javax.swing.JLabel lblobligatorio11;
    private javax.swing.JLabel lblobligatorio6;
    private javax.swing.JLabel lblobligatorio7;
    private javax.swing.JLabel lblobligatorio8;
    private javax.swing.JLabel lblobligatorio9;
    private javax.swing.JLabel lblobligatoriobuscarpa;
    private javax.swing.JTextField txtbuscarpacientes;
    private javax.swing.JTextField txtcolorpa;
    private javax.swing.JTextField txtdocumentocli1;
    private javax.swing.JTextField txtedadpa;
    private javax.swing.JTextField txtnombrepaci;
    private javax.swing.JTextField txtpesopa;
    private javax.swing.JTextField txtrazapa;
    // End of variables declaration//GEN-END:variables
}
